### ISSUE TITLE
hergebruik properties

### ISSUE THREAD

**Issue by lvdbrink** [provincieNH/OTL-BOR#11]
Misschien kunnen we meerdere keren voorkomende properties zoals kruinlijn, talud, één keer definiëren in plaats van een apart property voor elke klasse.  Wat is de reden om dat niet te doen?

**Comment by HansSchevers1975** [comment]
Geen directe reden om het (niet) te doen. Dit is even hoe het uit de "generator' komt. Ik ga er naar kijken.

**Comment by HansSchevers1975** [comment]
Nieuwe versie definieert minder kenmerken.
