### ISSUE TITLE
typfouten

### ISSUE THREAD

**Issue by lvdbrink** [provincieNH/OTL-BOR#12]
bij fysiek_voorkomen_open_verharding bij Wegdeel, OndersteunendWegdeel, OnbegroeidTerreindeel

imgeo:fysiek_voorkomenPlus_gebakker_klinkers

moet zijn: gebakken_klinkers met een n.

**Comment by lvdbrink** [comment]
Bij fysiek voorkomen begroeid terreindeel: 

imgeo:fysiek_voorkomen_naald_bos

Moet zijn naaldbos, één woord zonder spatie.
 
imgeo:fysiek_voorkomen_gemend_bos

Moet zijn gemengd_bos, met een g erin. 

imgeo:fysiek_voorkomen_moeral

Moet zijn moeras, met een s.

**Comment by lvdbrink** [comment]
Bij Kast: 

imgeo:typePlus_gml_kast

Moet zijn: gmi_kast met een i

**Comment by lvdbrink** [comment]
Bij Sensor: 

imgeo:typePlus_GML_sensor 

Moet zijn: GMS_sensor met een S

**Comment by HansSchevers1975** [comment]
verwerkt
