### ISSUE TITLE
Plaatsbepalingspunt ontbreekt

### ISSUE THREAD

**Issue by lvdbrink** [provincieNH/OTL-BOR#8]
De klasse Plaatsbepalingspunt komt niet voor in de IMGeo ontologie, maar zit wel in IMGeo.

Misschien is dit intentioneel, maar ik kan het me niet met zekerheid herinneren.

**Comment by lvdbrink** [comment]
Voor de volledigheid: deze heeft ook nog properties, nl
- nauwkeurigheid
- datumInwinning
- inwinnendeInstatie
- inwinningsmethode
Zie evt ook http://imgeo.geostandaarden.nl/def/imgeo-object/plaatsbepalingspunt

**Comment by HansSchevers1975** [comment]
Deze zit er nu in.
