### ISSUE TITLE
Ontbrekende properties

### ISSUE THREAD

**Issue by lvdbrink** [provincieNH/OTL-BOR#9]
Nummeraanduidingreeks (eigenschap van Pand)
NEN3610ID / identificatie
Label

**Comment by lvdbrink** [comment]
NEN3610ID is wel aanwezig.

**Comment by lvdbrink** [comment]
identificatieBAGPND ontbreekt (eigenschap van Pand). Dit is een string. In een linked data omgeving zou het een url naar een BAG pand zijn (bv bag.basisregistraties.overheid.nl/bag/id/pand/0307100000367968). Maar dat gaat voor nu te ver denk ik.

**Comment by HansSchevers1975** [comment]
Ik heb voor de vorm deze eigenschappen toegevoegd.
